#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Examen")]
	public partial class LQGenderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public LQGenderDataContext() : 
				base(global::DAL.Properties.Settings.Default.ExamenConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LQGenderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQGenderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQGenderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LQGenderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.actualizarGenero")]
		public int actualizarGenero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genderId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string label)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), genderId, label);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.agregarGenero")]
		public int agregarGenero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(45)")] string label)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), label);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarGenero")]
		public ISingleResult<consultarGeneroResult> consultarGenero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genderId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), genderId);
			return ((ISingleResult<consultarGeneroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.consultarGeneros")]
		public ISingleResult<consultarGenerosResult> consultarGeneros()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<consultarGenerosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarGenero")]
		public int eliminarGenero([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> genderId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), genderId);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class consultarGeneroResult
	{
		
		private int _genderId;
		
		private string _label;
		
		public consultarGeneroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderId", DbType="Int NOT NULL")]
		public int genderId
		{
			get
			{
				return this._genderId;
			}
			set
			{
				if ((this._genderId != value))
				{
					this._genderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="VarChar(45)")]
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				if ((this._label != value))
				{
					this._label = value;
				}
			}
		}
	}
	
	public partial class consultarGenerosResult
	{
		
		private int _genderId;
		
		private string _label;
		
		public consultarGenerosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genderId", DbType="Int NOT NULL")]
		public int genderId
		{
			get
			{
				return this._genderId;
			}
			set
			{
				if ((this._genderId != value))
				{
					this._genderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="VarChar(45)")]
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				if ((this._label != value))
				{
					this._label = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
